{
 "title": "Retail Review Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Number of drifted features over time",
   "type": "timeseries",
   "description": "This graph shows the number of drifted features predicted over batch data per day as batch service runs at the schedule",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT $__time(created_at), num_drifted_columns FROM model_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Missing values over time",
   "type": "timeseries",
   "description": "This graph shows the number of missing values on batch data predicted in days batch service runs at schedule",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT $__time(created_at), share_missing_values FROM model_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Average prediction drifts",
   "type": "gauge",
   "description": "This graph shows the average prediction drifts happened over time the batch service runs",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(prediction_drift) FROM model_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Average number of features drifting over time",
   "type": "stat",
   "description": "Graph shows the average number of features drifting overtime",
   "gridPos": { "h": 9, "w": 5, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(num_drifted_columns) FROM model_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Prediction drifts over time",
   "type": "timeseries",
   "description": "This graph shows the prediction drifts happening over time per day as batch service runs and saves metrics in the database",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT $__time(created_at), prediction_drift FROM model_metrics LIMIT 50 "
    }
   ]
  }
 ]
}