version: '3.8'

services:
  prefect:
    image: prefecthq/prefect:3.3.8.dev4-python3.10
    environment:
      - PREFECT_API_DATABASE_CONNECTION_URL=postgresql+asyncpg://sample:example@postgres:5432/training_prefect_db
      - PREFECT_API_URL=http://localhost:4200/api
    command: prefect server start --host 0.0.0.0
    ports:
      - "4200:4200"
    networks:
      - parent-tier

  mlflow:
    container_name: mlflow
    build:
      context: .
      dockerfile: docker/mlflow.dockerfile
    restart: always
    environment:
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=minio-root-user
      - AWS_SECRET_ACCESS_KEY=minio-root-password
    ports:
      - "5000:5000"
    command: >
      mlflow server
      --backend-store-uri postgresql://sample:example@postgres:5432/mlflow_db
      --default-artifact-root s3://mlflow/
      --host 0.0.0.0
      --port 5000
    networks:
      - parent-tier

networks:
  parent-tier:
    name: parent-tier
    external: true