apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: retail_db
    user: sample
    secureJsonData:
      password: 'example'
    jsonData:
      sslmode: 'disable'
      database: retail_db
